version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: itemite-postgres
    environment:
      POSTGRES_DB: ItemiteDB
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: itemite-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data: